
// This file has been generated by the GUI designer. Do not modify.
namespace aPlay_GUI
{
	public partial class LibraryViewer
	{
		private global::Gtk.Table table1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget aPlay_GUI.LibraryViewer
			global::Stetic.BinContainer.Attach (this);
			this.Name = "aPlay_GUI.LibraryViewer";
			// Container child aPlay_GUI.LibraryViewer.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(1)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview2 = new global::Gtk.TreeView ();
			this.treeview2.CanFocus = true;
			this.treeview2.Name = "treeview2";
			this.GtkScrolledWindow.Add (this.treeview2);
			this.table1.Add (this.GtkScrolledWindow);
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.treeview2.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTreeview2RowActivated);
		}
	}
}
